/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.swingproject;
//import javax.swing.JComboBox;
import java.awt.Color;
import java.sql.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Debnil
 */
public class FilterStockCheck extends javax.swing.JFrame {

    /**
     * Creates new form FilterStockCheck
     */
    String arr[];
    public FilterStockCheck(String a[]) {
        this.arr=a;
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.getContentPane().setBackground(Color.WHITE);
        nameBasedSearch.setVisible(false);
        quantityBasedSearch.setVisible(false);
        alphabetBasedSearch.setVisible(false);
        tableShow.setVisible(false);
        resultMessagePane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        heading = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGroups = new javax.swing.JPanel();
        nameButton = new javax.swing.JRadioButton();
        quantityButton = new javax.swing.JRadioButton();
        alphabetButton = new javax.swing.JRadioButton();
        nameBasedSearch = new javax.swing.JPanel();
        names = new javax.swing.JComboBox<>(arr);
        nameSearchBtn = new javax.swing.JButton();
        tableShow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        quantityBasedSearch = new javax.swing.JPanel();
        quantities = new javax.swing.JComboBox<>();
        quantitySearchbtn = new javax.swing.JButton();
        alphabetBasedSearch = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        resultMessagePane = new javax.swing.JPanel();
        resultMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        heading.setBackground(new java.awt.Color(0, 255, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Filter Stock Check");

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(nameButton);
        nameButton.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nameButton.setText("Name");
        nameButton.setToolTipText("");
        nameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(quantityButton);
        quantityButton.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        quantityButton.setText("Quantity");
        quantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(alphabetButton);
        alphabetButton.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        alphabetButton.setText("Alphabet");
        alphabetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphabetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonGroupsLayout = new javax.swing.GroupLayout(buttonGroups);
        buttonGroups.setLayout(buttonGroupsLayout);
        buttonGroupsLayout.setHorizontalGroup(
            buttonGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGroupsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(nameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quantityButton)
                .addGap(196, 196, 196)
                .addComponent(alphabetButton)
                .addGap(58, 58, 58))
        );
        buttonGroupsLayout.setVerticalGroup(
            buttonGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGroupsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(buttonGroupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityButton)
                    .addComponent(nameButton)
                    .addComponent(alphabetButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        nameBasedSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        nameSearchBtn.setText("Search");
        nameSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nameBasedSearchLayout = new javax.swing.GroupLayout(nameBasedSearch);
        nameBasedSearch.setLayout(nameBasedSearchLayout);
        nameBasedSearchLayout.setHorizontalGroup(
            nameBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameBasedSearchLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(nameSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        nameBasedSearchLayout.setVerticalGroup(
            nameBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameBasedSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tableShow.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout tableShowLayout = new javax.swing.GroupLayout(tableShow);
        tableShow.setLayout(tableShowLayout);
        tableShowLayout.setHorizontalGroup(
            tableShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableShowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        tableShowLayout.setVerticalGroup(
            tableShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableShowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        quantityBasedSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        quantities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<10", "<15", "<20", ">20" }));

        quantitySearchbtn.setText("Search");
        quantitySearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitySearchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quantityBasedSearchLayout = new javax.swing.GroupLayout(quantityBasedSearch);
        quantityBasedSearch.setLayout(quantityBasedSearchLayout);
        quantityBasedSearchLayout.setHorizontalGroup(
            quantityBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quantityBasedSearchLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(quantities, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quantitySearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        quantityBasedSearchLayout.setVerticalGroup(
            quantityBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quantityBasedSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quantityBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantities, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantitySearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        alphabetBasedSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 255)));

        searchField.setText("search here");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout alphabetBasedSearchLayout = new javax.swing.GroupLayout(alphabetBasedSearch);
        alphabetBasedSearch.setLayout(alphabetBasedSearchLayout);
        alphabetBasedSearchLayout.setHorizontalGroup(
            alphabetBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alphabetBasedSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        alphabetBasedSearchLayout.setVerticalGroup(
            alphabetBasedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alphabetBasedSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        resultMessage.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resultMessage.setText("No Result Found");

        javax.swing.GroupLayout resultMessagePaneLayout = new javax.swing.GroupLayout(resultMessagePane);
        resultMessagePane.setLayout(resultMessagePaneLayout);
        resultMessagePaneLayout.setHorizontalGroup(
            resultMessagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultMessagePaneLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(resultMessage)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        resultMessagePaneLayout.setVerticalGroup(
            resultMessagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultMessagePaneLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(resultMessage)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameBasedSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(quantityBasedSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGroups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(alphabetBasedSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultMessagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGroups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(nameBasedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityBasedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alphabetBasedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultMessagePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void getStock(int no,String n){
        tableShow.setVisible(true);
        Connection conn=new GetConnection().getConnection();
        try{
            switch (no) {
                case 1:
                    PreparedStatement ps1=conn.prepareStatement("select name,quantity from medicines where name=?");
                    ps1.setString(1, n);
                    ResultSet rs=ps1.executeQuery();
                    table.setModel(DbUtils.resultSetToTableModel(rs));
                    break;
                case 2:
                    String symbol=n.substring(0,1);
                    int quan=Integer.parseInt(n.substring(1));
                    PreparedStatement ps2=conn.prepareStatement("select name,quantity from medicines where quantity"+symbol+"?");
                    ps2.setInt(1, quan);
                    ResultSet rs1=ps2.executeQuery();
                    table.setModel(DbUtils.resultSetToTableModel(rs1));
                    break;
                case 3:
                    
                    break;
                default:
                    break;
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    private void quantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityButtonActionPerformed
        // TODO add your handling code here:
        nameBasedSearch.setVisible(false);
        quantityBasedSearch.setVisible(true);
        alphabetBasedSearch.setVisible(false);
        tableShow.setVisible(false);
//        resultSet.setVisible(false);
    }//GEN-LAST:event_quantityButtonActionPerformed

    private void nameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameButtonActionPerformed
        // TODO add your handling code here:
        nameBasedSearch.setVisible(true);
        quantityBasedSearch.setVisible(false);
        alphabetBasedSearch.setVisible(false);
        tableShow.setVisible(false);
//        resultSet.setVisible(false);

    }//GEN-LAST:event_nameButtonActionPerformed

    private void alphabetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphabetButtonActionPerformed
        // TODO add your handling code here:
        nameBasedSearch.setVisible(false);
        quantityBasedSearch.setVisible(false);
        alphabetBasedSearch.setVisible(true);
        tableShow.setVisible(false);
//        resultSet.setVisible(false);
    }//GEN-LAST:event_alphabetButtonActionPerformed

    private void nameSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchBtnActionPerformed
        // TODO add your handling code here:
        String name=(String)names.getSelectedItem();
        getStock(1,name);
    }//GEN-LAST:event_nameSearchBtnActionPerformed

    private void quantitySearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitySearchbtnActionPerformed
        // TODO add your handling code here:
        String quan=(String)quantities.getSelectedItem();
        getStock(2,quan);
    }//GEN-LAST:event_quantitySearchbtnActionPerformed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
      
    }//GEN-LAST:event_searchFieldKeyPressed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldKeyTyped

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
//        tableShow.setVisible(true);
        Connection conn=new GetConnection().getConnection();
        try{
        PreparedStatement ps=conn.prepareStatement("select name,quantity from medicines where name like ?");
        System.out.println(searchField.getText());
        if(searchField.getText().equals("")==true){
            tableShow.setVisible(false);
            return;
        }
        String q="%"+searchField.getText()+"%";
        System.out.println(q);
        ps.setString(1, q);
//        String result="";
        ResultSet rs=ps.executeQuery();
        if(rs.next()){
            tableShow.setVisible(true);
            resultMessagePane.setVisible(false);
            ResultSet rs1=ps.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs1));
        }
        else{
            tableShow.setVisible(false);
            resultMessagePane.setVisible(true);
        }
//        resultSet.setVisible(true);
//        while(rs.next()){
//            result=result+rs.getString("name")+"          "+rs.getInt("quantity")+"\n";
//        }
//        System.out.println(result);
//        resultSet.setText(result);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_searchFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alphabetBasedSearch;
    private javax.swing.JRadioButton alphabetButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttonGroups;
    private javax.swing.JPanel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nameBasedSearch;
    private javax.swing.JRadioButton nameButton;
    private javax.swing.JButton nameSearchBtn;
    private javax.swing.JComboBox<String> names;
    private javax.swing.JComboBox<String> quantities;
    private javax.swing.JPanel quantityBasedSearch;
    private javax.swing.JRadioButton quantityButton;
    private javax.swing.JButton quantitySearchbtn;
    private javax.swing.JLabel resultMessage;
    private javax.swing.JPanel resultMessagePane;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable table;
    private javax.swing.JPanel tableShow;
    // End of variables declaration//GEN-END:variables
}
